{% set name = "fair" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e1ff72e09a577eec152a27727a236045462c41e6927011bc4715135efb3693f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy
    - pandas
    - pooch
    - scipy
    - tqdm
    - xarray

test:
  imports:
    - fair

about:
  home: https://github.com/OMS-NetZero/FAIR
  license: Apache-2.0
  license_file: LICENSE
  summary: Finite-amplitude Impulse Response simple climate model.

  description: |
    FaIR (the Finite-amplitude Impulse-Response) climate model is a
    simple climate model, or emulator, useful for producing global
    mean temperature projections from a wide range of emissions or
    prescribed forcing scenarios. 
  dev_url: https://github.com/OMS-NetZero/FAIR

extra:
  recipe-maintainers:
    - bjlittle
    - chrisroadmap
